ansh/jiffyreader.com

src/popup.js
I found that this method works on more pages.
=> Convert all tags instead of just the one with most content

src/convert.js
https://github.com/ansh/bionic-reading/issues/23
=> feat: rules 2, 3, 4, 7

src/convert.js
https://github.com/ansh/bionic-reading/issues/23
=> feat: rule 5

manifest.json, src/background.js
I don't like cluttering up my toolbar with too many extension icons, so keyboard shortcuts for little ones like this are quite useful imo.
Maybe the script call is worth extracting into a function since it's repeated a few times, but I didn't want to take it upon myself to refactor.
=> feat: add keyboard shortcut

.github/ISSUE_TEMPLATE.md
Added a basic issue template that fixes #62. Feel free to add more info if needed.
=> Create ISSUE_TEMPLATE.md, fixes #62

package.json, src/Background/index.js, src/ContentScript/index.js, src/Popup/index.js, src/style.css, views/popup.html, webpack.config.js, yarn.lock
fix for issue #73 
@ansh @X140Yu can you take a look
Feat included onoff button
=> Fix issue#73 broken toggle

src/Popup/index.js
The extension does not work in Yandex browser. I do not develop browser extensions, so my solution to the problem may be incorrect. However, after these changes, everything worked, I also tested it in Google Chrome.
=> Fix for Yandex Browser.

README.md
Remove the deprecated installation instructions from the README
=> Remove deprecated installation instructions from README

src/ContentScript/index.js, src/ContentScript/observer.js
attempt to address #114 
issues these address I think? are:
- thumbnail names not updated on the homepage 
- never ending duplicate labels and titles as you navigate and traverse youtube
- suggestions video title not updating on the side bar
I've added some detailed comments and super curious what you guys think as I particularly don't like having to create an observer for each text node. 
the main Idea I had for this is to keep the text node alive because I noticed youtube has some internal reference to the text node. and if we removed it. it won't update the text anymore causing the stale titles.
=> keep textnode alive

src/Popup/index.js, src/Preferences/index.js, src/manifest.json, src/style.css, views/popup.html
chrome extension store blocked an update due to the presence of storage permissions which is no longer used and has been removed from manifest.json
=> fix: removed unused permission and replace saccades color and style options with drop downs 

package.json, src/Background/index.js, src/Bookmarklet/index.js, src/ContentScript/contentStyle.scss, src/ContentScript/documentParser.js, src/ContentScript/index.js, src/Popup/index.js, src/Preferences/index.js, src/TabHelper.js, views/popup.html
production build was breaking due to using promises to send responses to sendMessage calls.
=> fix: broken production build

.github/workflows/publish-release-on-tag.yml, .github/workflows/run-tests.yml, README.md, package.json, src/Background/index.js, src/Bookmarklet/esbuild.js, src/Bookmarklet/index.js, src/ContentScript/index.js, src/Logger.js, src/Popup/index.js, src/Preferences/index.js, src/manifest.json, views/popup.html, webpack.config.js
Update: enhance ui with descriptive text
Fix: buggy toggles in popup when on global prefs
Update(dev): actions test
Update(dev): add separate and enhaced build scripts for github actions
update(dev): add dev:bookmarklet to package.json
=> Fix: popup buttons not responding and improvements

.github/workflows/publish-release-on-tag.yml
caused by not interpolating variables into string properly in the action script
=> Fix: package.json build error

src/Background/index.js, src/Bookmarklet/esbuild.js, src/Bookmarklet/index.js, src/ContentScript/contentStyle.scss, src/ContentScript/documentParser.js, src/ContentScript/index.js, src/Popup/index.js, src/Preferences/index.js, src/style.css, views/popup.html
minor function and minor aesthetic update
Popup now servers as preview to see the effect of choose configurations.
=> updated popup ui, fixation split enhancements and bookmarklet update

src/ContentScript/documentParser.js
observer code seems to have been stuck in a loop
add a precheck to exit an observe call if an textarea:focus or input:focus is present
=> Fix: github textarea freezing while typing

README.md
=> Update(docs): indicate the default reading mode is off

src/ContentScript/siteElementExclusions.js
Broken grammarly input and data loss
Fixes #156
=> Fix: issue#156 Broken grammarly input and data loss

README.md
=> Fix(doc): broken about link

.vscode/tasks.json, README.md, assets/_locales/en/messages.json, assets/_locales/es/messages.json, package.json, src/popup/index.tsx, src/styles/style.scss
Added support for localizing and supporting translations.
=> Feat: internationationalize and localize

README.md
Ready but hold on to merge till end of day 11/08/2022
=> Update(docs): expand welcome section

assets/_locales/en/messages.json, src/popup/index.tsx, src/styles/style.scss
show actionable messages based on type of error occuring
Feat: show multiple messages in footer
=> Update: improve error messages

README.md
Corrected some typos in the readme file and cleaned up a few small phrasing issues.
=> Corrected typos in Readme

src/services/siteElementExclusions.ts
add exclusion for all domains blocking input, [contenteditable], [role=textbox]
remove redundant exclusion for twitter, facebook, whatsapp
=> Fix buggy editable inputs

index.d.ts, src/background/index.ts, src/contents/content.tsx, src/popup/indexNew.tsx, src/popup/indexOld.tsx, src/services/documentParser.ts, src/services/preferences.ts, src/services/siteElementExclusions.ts, src/services/usePrefs.tsx
* Feat: add latex check
Chore: improve makeExcluder, add textarea to globally excluded elements
* Update: delay auto on when latex is present
* Update: declare autoOnDelay on default prefs
* Update: rewrite saved prefs when app is installed or updated
* Chore: simplify and type code
* Chore: improve index.d.ts
* Chore: update types
* Chore: fix typo
=> Fix/latex auto on bug (#8)

index.d.ts, src/background/index.ts, src/popup/index.tsx, src/services/TrackEventService.ts
open welcome page if installed version is new
add activity tracking
=> Improve post install behaviour

.gitignore, README.md, package.json, src/background/index.ts, src/constants.ts, src/contents/content_script.ts, src/popup/indexNew.tsx, src/popup/indexOld.tsx, yarn.lock
integrate open source mellowtel.dev library to support free plugins
=> integrate library
